language: generic

services:
    - docker

branches:
    only:
        - master

before_install:
    - openssl aes-256-cbc -K $encrypted_6196c450fde8_key -iv $encrypted_6196c450fde8_iv
        -in deploy_rsa.enc -out deploy_rsa -d

script:
    - make all

deploy:
    -
        provider: script
        on:
            branch: master
        script: 'rsync --archive htdocs/ hwd@xn--d1alp.xn--80asehdb:htdocs/'
