##
## Настройки для запуска сайта на локальной машине.
##

version: '3.2'

services:

    ## Веб-сервер и сам сайт.
    web:
        build:
            context: sphinx
        ports:
            - 8000:8000
        volumes:
            - './src/pages:/opt/docs:ro'
            - './htdocs/pages:/var/www/html/pages'
        working_dir: '/opt/docs'
        command: sphinx-autobuild --poll -H 0.0.0.0 /opt/docs /var/www/html/pages
