##
## Настройки для запуска сайта на локальной машине.
##

version: '3'

services:

    ## Веб-сервер и сам сайт.
    web:
        image: dobrosite/php:${DOCKER_PHP_VERSION}-apache
        ports:
            - ${DOCKER_SITE_PORT}:80
        environment:
            APACHE_MODULES: ${DOCKER_APACHE_MODULES}
            FILE_OWNER_UID: ${UID}
            PHP_EXTENSIONS: ${DOCKER_PHP_EXTENSIONS} xdebug
            PHP_INI_SETTINGS: ${DOCKER_PHP_INI_SETTINGS}
            NULLMAILER_REMOTES: 'mail smtp --port=1025'
            SYMFONY_ENV: dev
            SYMFONY_DEBUG: 1
        volumes:
            - './develop/vhost.conf:/etc/apache2/sites-enabled/000-default.conf:ro'
            - './:/var/www/site'
        working_dir: /var/www/site

    ## Сервер MySQL/MariaDB.
    mysql:
        image: dobrosite/mysql:${DOCKER_MYSQL_VERSION}
        environment:
            FILE_OWNER_UID: ${UID}
            MYSQL_ROOT_PASSWORD: root
            # Настройка имени БД сайта и доступа к ней.
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            # Папка для размещения файлов БД.
            - './docker/var/db:/var/lib/mysql'
            # Папка с дополнительными файлами.
            - './db:/usr/local/mysql'

    ## phpMyAdmin.
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:latest
        volumes:
            - /sessions
        ports:
            - ${DOCKER_PMA_PORT}:80
        environment:
            - PMA_HOST=mysql
            - PMA_USER=user
            - PMA_PASSWORD=password

    ## Перехватывающий почтовый сервер.
    mail:
        image: mailhog/mailhog:latest
        ports:
            - ${DOCKER_WEBMAIL_PORT}:8025
