##
## Настройки для запуска сайта на тестовой площадке dobrotest.site.
##
## Для работы требуется nginx-proxy: https://github.com/jwilder/nginx-proxy/
##

version: '3'

services:

    ## Веб-сервер и сам сайт.
    web:
        restart: always
        image: dobrosite/php:${DOCKER_PHP_VERSION}-apache
        expose:
            # Открываем порт для nginx-proxy.
            - 80
        environment:
            APACHE_MODULES: ${DOCKER_APACHE_MODULES}
            FILE_OWNER_UID: ${UID}
            PHP_EXTENSIONS: ${DOCKER_PHP_EXTENSIONS}
            PHP_INI_SETTINGS: ${DOCKER_PHP_INI_SETTINGS}
            NULLMAILER_REMOTES: 'mail smtp --port=1025'
            SYMFONY_ENV: test
            SYMFONY_DEBUG: 0
            VIRTUAL_HOST: ${SITE_DOMAIN}.dobrotest.site
        volumes:
            - './htdocs:/var/www/html'
        networks:
            - default
            - nginx-proxy

    ## Сервер MySQL/MariaDB.
    mysql:
        restart: always
        image: dobrosite/mysql:${DOCKER_MYSQL_VERSION}
        environment:
            FILE_OWNER_UID: ${UID}
            MYSQL_ROOT_PASSWORD: root
            # Настройка имени БД сайта и доступа к ней.
            MYSQL_DATABASE: database
            MYSQL_USER: user
            MYSQL_PASSWORD: password
        volumes:
            # Папка для размещения файлов БД.
            - './docker/var/db:/var/lib/mysql'
            # Папка с дополнительными файлами.
            - './db:/usr/local/mysql'

    ## phpMyAdmin.
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin:latest
        volumes:
            - /sessions
        expose:
            - 80
        environment:
            VIRTUAL_HOST: pma.${SITE_DOMAIN}.dobrotest.site
            PMA_HOST: mysql
            PMA_USER: user
            PMA_PASSWORD: password
        networks:
            - default
            - nginx-proxy

    ## Перехватывающий почтовый сервер.
    mail:
        image: mailhog/mailhog:latest
        expose:
            - 8025
        environment:
            VIRTUAL_HOST: mail.${SITE_DOMAIN}.dobrotest.site
        networks:
            - default
            - nginx-proxy

# Дополнительные виртуальные сети.
networks:
    # Сеть, позволяющая маршрутизацию с помощью nginx-proxy.
    nginx-proxy:
        external:
            name: nginx-proxy
